from __future__ import annotations

import argparse
import json
from pathlib import Path


def parse_args() -> argparse.Namespace:
  parser = argparse.ArgumentParser(description="Validate backend coverage thresholds.")
  parser.add_argument(
    "--input",
    default="backend/coverage.json",
    help="Path to coverage JSON report generated by coverage.py/pytest-cov.",
  )
  parser.add_argument(
    "--min-statements",
    type=float,
    default=50.0,
    help="Minimum statements coverage percentage required to pass.",
  )
  return parser.parse_args()


def main() -> int:
  args = parse_args()
  report_path = Path(args.input)
  if not report_path.exists():
    raise SystemExit(f"Coverage report not found: {report_path}")

  report = json.loads(report_path.read_text(encoding="utf-8"))
  totals = report.get("totals") or {}
  statement_percent = float(totals.get("percent_covered", 0.0))
  minimum = float(args.min_statements)

  print(
    f"Coverage gate: statements={statement_percent:.2f}% "
    f"(required >= {minimum:.2f}%)"
  )

  if statement_percent < minimum:
    raise SystemExit(
      f"Coverage below threshold: {statement_percent:.2f}% < {minimum:.2f}%"
    )

  return 0


if __name__ == "__main__":
  raise SystemExit(main())
