"""Barrel export for domain-scoped repository modules."""

from app.db.repos.auth_repo import (
    create_idempotency_key,
    create_refresh_token_record,
    get_idempotency_key,
    get_refresh_token_by_hash,
    revoke_all_refresh_tokens_for_user,
    revoke_refresh_token,
)
from app.db.repos.entity_repo import (
    RESOURCE_MODELS,
    SYNC_ENTITY_MODELS,
    apply_server_revision,
    find_appointment_conflict,
    get_active_by_id,
    get_inventory_by_sku,
    get_inventory_by_sku_for_update,
    get_user_by_email,
    list_active,
    list_invoice_items,
    mark_deleted,
    touch_for_update,
    utc_now,
)
from app.db.repos.sync_repo import (
    advance_device_cursor,
    append_audit_log,
    append_sync_event,
    claim_entity_field_clock,
    enqueue_conflict,
    ensure_monotonic_device_cursor,
    get_conflict_by_operation_id,
    get_sync_event_by_operation_id,
    latest_server_revision,
    list_conflicts,
    list_sync_event_audit_since,
    list_sync_events_since,
    resolve_conflict,
)
from app.db.repos.tenant_repo import (
    assign_user_tenant,
    create_tenant,
    get_tenant,
    list_tenants,
    set_tenant_active,
)

__all__ = [
    "RESOURCE_MODELS",
    "SYNC_ENTITY_MODELS",
    "utc_now",
    "list_active",
    "get_active_by_id",
    "get_user_by_email",
    "get_inventory_by_sku",
    "get_inventory_by_sku_for_update",
    "list_invoice_items",
    "find_appointment_conflict",
    "touch_for_update",
    "mark_deleted",
    "apply_server_revision",
    "append_sync_event",
    "get_sync_event_by_operation_id",
    "latest_server_revision",
    "ensure_monotonic_device_cursor",
    "advance_device_cursor",
    "claim_entity_field_clock",
    "list_sync_events_since",
    "list_sync_event_audit_since",
    "get_conflict_by_operation_id",
    "enqueue_conflict",
    "list_conflicts",
    "resolve_conflict",
    "append_audit_log",
    "create_tenant",
    "list_tenants",
    "get_tenant",
    "assign_user_tenant",
    "set_tenant_active",
    "get_refresh_token_by_hash",
    "revoke_refresh_token",
    "get_idempotency_key",
    "create_idempotency_key",
    "revoke_all_refresh_tokens_for_user",
    "create_refresh_token_record",
]
